version: 2.1

orbs:
  maven: circleci/maven@1.0.1

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results

      steps:
        name: Send to CodeCov
        command: bash <(curl -s https://codecov.io/bash)